### ISSUE TITLE
jikanpy installation

### ISSUE THREAD

**Issue by adit2789** [AWConant/jikanpy#1]
Hello, I am having some issues installing this jikanpy. Most packages are supposed to have a setup.py file to help install it, but I do not see one anywhere in the file structure. Does this require some other form of installation besides pip or easy_install?

Also, does this work on python 3+, I do not see anything in the documentation

**Comment by abhinavk99** [comment]
Do `pip install -r requirements.txt` in the root directory to install all the packages from requirements.txt

As for your other question, it worked on python 3.6 for me.

**Comment by abhinavk99** [comment]
Closing since it's been 7 months with no response
