### ISSUE TITLE
Support for anime/manga list of a user

### ISSUE THREAD

**Issue by m4st3rP** [AWConant/jikanpy#11]
Hello,
I would suggest adding the possibility to get the anime and/or manga of a user (so basically this JSON: https://api.jikan.moe/v3/user/masterP/animelist).
If this already exists, then I am really sorry, I searched for it but couldn't find it.
Thank you very much!

**Comment by abhinavk99** [comment]
Thanks for making the issue. Jikanpy currently adheres to Jikan REST v3.0, so I need to update it to adhere to v3.1, which added anime and manga lists of a user.

**Comment by abhinavk99** [comment]
Just added support in 6035f9b.

Use it as such:
```python
anime = jikan.user(username='masterP', request='animelist')
manga = jikan.user(username='masterP', request='mangalist')
anime_ptw = jikan.user(username='masterP', request='animelist', argument='ptw')
pg_number = jikan.user(username='masterP', request='mangalist', argument='reading', page=2)
```
