### ISSUE TITLE
Animelist paging doesn't seem to work

### ISSUE THREAD

**Issue by m4st3rP** [AWConant/jikanpy#13]
Hello again,
when I set the page while retrieving an animelist the number did not matter, it would always get the first page. I tried using different arguments or leaving it out completely but the issues persisted.
Here is how I tried it:
`
animelist = jikan.user(username='masterP', request='animelist', argument='completed', page=2)
animelist = jikan.user(username='masterP', request='animelist', argument='all', page=3)
animelist = jikan.user(username='masterP', request='animelist', page=4)
`

**Comment by abhinavk99** [comment]
Sorry about that, I didn't implement paging correctly. Also, you can't provide a page unless you provide an argument for 'animelist' or 'mangalist' because https://api.jikan.moe/v3/user/masterP/animelist/4 is not a valid endpoint.

**Comment by abhinavk99** [comment]
Just fixed paging in dde348e
