### ISSUE TITLE
Error running example code: get() takes no keyword arguments

### ISSUE THREAD

**Issue by the-bmb** [AWConant/jikanpy#14]
![image](https://user-images.githubusercontent.com/19418672/48666311-50733b80-eaa6-11e8-8cde-37794959068b.png)

**Comment by abhinavk99** [comment]
Sorry about that, I just fixed this in the most recent commit, 85a4055. Please run `pip install git+git://github.com/AWConant/jikanpy.git` again to get the newest version.

**Comment by the-bmb** [comment]
Now show this error:
![image](https://user-images.githubusercontent.com/19418672/48713567-cf2bbe00-ebf7-11e8-821c-f9968b93d781.png)
