### ISSUE TITLE
Error running example code: can't convert int

### ISSUE THREAD

**Issue by the-bmb** [AWConant/jikanpy#15]
![image](https://user-images.githubusercontent.com/19418672/48786319-c7d6e400-eccd-11e8-8fd5-635d72c281fa.png)

**Comment by abhinavk99** [comment]
I should have tested the code more rigorously, sorry again.

**Comment by the-bmb** [comment]
No problem, if I have time I correct in a PR, thank you

**Comment by abhinavk99** [comment]
Just fixed this in commit ac36630.
