### ISSUE TITLE
Provide Continuous Integration Build Status

### ISSUE THREAD

**Issue by erayerdin** [AWConant/jikanpy#17]
I think it is better to provide a continuous integration build status just to inform the community about if build/tests pass or not.

TravisCI is a common CI tool for open-source project. If you allow, I can provide PR about this. You might need to create a Travis account though.

**Comment by abhinavk99** [comment]
You're right, CI would be great. I would appreciate a PR since I have no clue on where to get started with setting it up.

**Comment by abhinavk99** [comment]
If it requires a Travis account, it might be better for me to set it up. Do you think you can still make a PR?

**Comment by erayerdin** [comment]
By the way, it doesn't seem like you have to create an account first. It seems like I can do whatever I can do with Travis without you creating one.

There is one issue, though, and it is that `aiohttp` dependency supports Python 3.4 with versions up to `2.3.10` but you have provided usage about Python 3.5 below versions on readme.

This does not mean it does not work with Python 3.4, maybe you have tested it by hand.

I execute tests starting from Python 3.5, hoping that it will not be an issue. It shouldn't be an issue since Python has a better stance about async and typing system starting from Python 3.5.

**Comment by abhinavk99** [comment]
I'm going to remove Python 3.4 from the README.

**Comment by abhinavk99** [comment]
Closing since #20 has been merged.
