### ISSUE TITLE
Search implementation constrained to one key/value pair

### ISSUE THREAD

**Issue by tybug** [AWConant/jikanpy#23]
The implementation of the search endpoint has no support for multiple keys/value pairs: https://github.com/AWConant/jikanpy/blob/master/jikanpy/jikan.py#L19

ie, I cannot search for both status=airing&rated=g, as the documentation suggests I can: https://jikan.docs.apiary.io/#reference/0/search

I can PR a fix for this (change to a dict of key/value pairs?) if needed, but I wanted to make sure I wasn't missing something obvious first

**Comment by abhinavk99** [comment]
That's my fault, I forgot to allow multiple pairs. I would appreciate a PR as I am busy this week.
