### ISSUE TITLE
Update wrapper to work with Jikan REST v3.2

### ISSUE THREAD

**Issue by abhinavk99** [AWConant/jikanpy#28]

**Comment by irfan-dahir** [comment]
That was fast! :D

I wrote a quick specification issue for dev wrappers and was just about to create the issue here. Here's that for reference/updates. :)

**Comment by irfan-dahir** [comment]
## New Features
- Anime/Manga Reviews, Recommendations, User Updates
- Club Information, Members
- Season Later

## Specification
### Reviews
**Anime**
```
GET /v3/anime/{id}/reviews/{page}
```
**Manga**
```
GET /v3/anime/{id}/reviews/{page}
```

**Remarks:** Only 20 items are shown per page for reviews


### Recommendations
**Anime**
```
GET /v3/anime/{id}/recommendations
```
**Manga**
```
GET /v3/anime/{id}/recommendations
```

### User Updates
**Anime**
```
GET /v3/anime/{id}/userupdates/{page}
```
**Manga**
```
GET /v3/anime/{id}/userupdates/{page}
```

### Season Later
```
GET /v3/season/later
```

### Club Information
```
GET /v3/club/{id}
```

### Club Members
```
GET /v3/club/{id}/members
```

## Changes
- All data from user related endpoints /v3/user/* are now cached for 5 minutes only
- (Anime/Manga) Bug fixed for related property. It's an object but returns an array when it was empty. This is fixed now.
- Error messages are now different and readable.


**Documentation:** https://jikan.docs.apiary.io

**Comment by abhinavk99** [comment]
I have Discord notifications on so I made the issue right when I saw the announcement haha

**Comment by abhinavk99** [comment]
Done.
