### ISSUE TITLE
[Feature Request] Get affinity with friends

### ISSUE THREAD

**Issue by sam5558** [AWConant/jikanpy#42]
Hello,
First of all, thanks for this interesting project.
I'm wondering if there's a way to get affinity with friends ? If we can use this syntax and get a metric with affinity percentage of each friend that would be great i think. Maybe this issue can be flagged with `improvement` flag if it's not available right now.
Target code :
`# friends info`
`myfriends = jikan.user(username='Guts__', request='friends')`

But anyway great project.

**Comment by abhinavk99** [comment]
This project is just a Pintos wrapper for the Jikan API, which can be found at https://github.com/jikan-me/jikan. I recommend you make a feature request there, and if it gets implemented I'll add to this wrapper.

**Comment by sam5558** [comment]
Thanks @abhinavk99 , you're right.

**Comment by abhinavk99** [comment]
Closing since I can't do anything about this.
