### ISSUE TITLE
change error message for .meta() ClientException

### ISSUE THREAD

**Issue by seanbreckenridge** [AWConant/jikanpy#52]
The typing hint for `type` argument in `meta` is Optional[int]/default is None, but if `request="requests"`, the type is required.

```

meta(request: str, type: Union[str, NoneType] = None, period: Union[str, NoneType] = None, offset: Union[int, NoneType] = None) -> Dict method of jikanpy.jikan.Jikan instance
    Gets meta information regarding the Jikan REST API

    Keyword Arguments:
    request -- requests (requests, status)
    type -- type to get info on, possible values in docs
    period -- time period (today, weekly, monthly)

```

I realize this is because you can pass `request="status"`, so the `type`/`period` cant be required.

The type hints would lead to believe that something like:

`jikanpy.Jikan().meta(request="requests")` is valid, 

but that throws the error:

```
  File "/Users/sean/.local/share/virtualenvs/jikanpy_ext-PEUtWLmH/lib/python3.7/site-packages/jikanpy/abstractjikan.py", line 263, in _get_meta_url
    raise ClientException("Type is not valid")
jikanpy.exceptions.ClientException: Type is not valid
```

I dont think changing the type hints makes sense/splitting this into 2 functions makes sense, maybe an extra error check [here](https://github.com/AWConant/jikanpy/blob/master/jikanpy/abstractjikan.py#L262) that checks if `type is None or period is None` and has a better error message, like:

'type' and 'period' are required for the "request" request

would be nice.

What do you think?

**Comment by abhinavk99** [comment]
Yeah that sounds like a good idea, thanks for taking time to research this. I'm probably gonna be busy for the next few days, so I can't work on it just yet. If you could make a PR that would be great, otherwise I'll do it sometime soon.

**Comment by abhinavk99** [comment]
@purplepinapples tagging you so i can assign
