### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by seanbreckenridge** [AWConant/jikanpy#55]
Hi, I've been using this for months and only just realized this project doesn't have a License on it. Could I request we add one?

Perhaps MIT since thats what [jikan](https://github.com/jikan-me/jikan-rest) uses.

@AWConant @abhinavk99 

If you wish, I can make the PR

**Comment by abhinavk99** [comment]
+1 for MIT

**Comment by abhinavk99** [comment]
I don't even think we need a PR, I can just click an add license button in the settings.

**Comment by abhinavk99** [comment]
@AWConant Just bumping this, are you okay if we make the license for this MIT?

**Comment by AWConant** [comment]
Yup, absolutely.
