### ISSUE TITLE
Add limit as a parameter of search function?

### ISSUE THREAD

**Issue by aidan-walden** [AWConant/jikanpy#61]
The Jikan API itself has support for limiting the amount of returned search results. (https://jikan.docs.apiary.io/#reference/0/search , under advanced search parameters), but the jikanpy wrapper does not. It could be useful for cases when you only need the first result, among other scenarios. Are there any plans to add this anytime in the future?

**Comment by abhinavk99** [comment]
You can use the parameters keyword argument on the search method like the below:

```python
from jikanpy import Jikan
jikan = Jikan()
result = jikan.search('anime', 'Naruto', parameters={'limit': 1})
```

**Comment by abhinavk99** [comment]
Closing since the question has been answered
