### ISSUE TITLE
Forum Topic Sub-Selection (Episode and Other)

### ISSUE THREAD

**Issue by tableaukun** [AWConant/jikanpy#62]
Hello! It appears MAL forums have two options for episode discussions (episode) and miscellaneous discussion (other). The [Jikan REST API](https://github.com/jikan-me/jikan-rest/issues/71#issuecomment-552444298) appears to have added this functionality by adding **/episodes** after /forum, with the added benefit of ordering the topics in episode descending order. Ex: https://api.jikan.moe/v3/anime/21/forum/episodes.

Is this feature easy to add? Thanks!

**Comment by abhinavk99** [comment]
Thanks for the heads up, it should be easy to add.

**Comment by abhinavk99** [comment]
Just finished this in v3.4.2, just use the extension `forum/episodes` as shown below:
```python
from jikanpy import Jikan
jikan = Jikan()

forum_episodes = jikan.anime(1, extension='forum/episodes')
```

**Comment by tableaukun** [comment]
@abhinavk99 sorry to raise this ticket again. Would it be possible to add `forum/other` as an extension as well?

**Comment by abhinavk99** [comment]
Sure, thanks for letting me know.
