### ISSUE TITLE
jikanpy.exceptions.APIException: 502

### ISSUE THREAD

**Issue by Neonz27** [AWConant/jikanpy#63]
I can not seem to get this API to work now for some strange reason. I just made a program that used it and it worked for the time, but when I tried it again a few hours later without changing the code at all it started giving the following output.

`C:\Users\<User>\Desktop\Development\mal-interface>python test.py
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    test()
  File "test.py", line 8, in test
    search_result = jikan.search("anime", search)
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python38\lib\site-packages\jikanpy\jikan.py", line 67, in search
    return self._wrap_response(response, url, **kwargs)
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python38\lib\site-packages\jikanpy\jikan.py", line 32, in _wrap_response
    self._check_response(
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python38\lib\site-packages\jikanpy\abstractjikan.py", line 74, in _check_response
    raise APIException(err_str)
jikanpy.exceptions.APIException: 502 : error for search type=anime, query=Fullmetal Alchemist: Brotherhood`

This is the test code I put together to receive that output without all of the other code being used by my application getting in the way.

`import json`
`from jikanpy import Jikan`

`def test():`
    `# jikan = Jikan(use_ssl = True)`
    `# jikan = Jikan(use_ssl = False)`
    `jikan = Jikan()`

    search = str(input("Choose An Anime: "))
    search_results = jikan.search("anime", search)
    print(json.loads(json.dumps(search_results))["results"])

`if __name__ == "__main__":`
    `# main()`
    `test()`

**Comment by seanbreckenridge** [comment]
The API itself is down currently, not an issue with your code. If you join the [discord](https://discordapp.com/invite/4tvCr36), you'll find many people with the same issue.

**Comment by irfan-dahir** [comment]
The issue was server side and has been resolved, thanks for reporting. 
Please [open an issue here](https://github.com/jikan-me/jikan) if you face the problem again.

**Comment by abhinavk99** [comment]
Closing since it seems like it's been resolved.
