### ISSUE TITLE
Get 2nd page of friends from user in myanimelist

### ISSUE THREAD

**Issue by sam5558** [AWConant/jikanpy#64]
Hello @AWConant ,
Thank you for your code, i'm currently using it to get my best affinities in my friends.
The thing is, right now, i'm only able to get affinity for my last active friends (basically page 1 of friends).
I've tried setting up a command to fetch the 2nd page of my friends :  
`ufriends2 = jikan.user(username='myuser', request='friends', page="2")`

But it just doesn't work, it seems all it can get is the first page, which is odd in a way.
Can you tell me if i'm missing something ? 
Thank you again,

**Comment by seanbreckenridge** [comment]
If you check the help:

```
>>> from jikanpy import Jikan
>>> j = Jikan()
>>> help(j.user)
```

```
Help on method user in module jikanpy.jikan:

user(username: str, request: Union[str, NoneType] = None, argument: Union[int, str, NoneType] = None, page: Union[int, NoneType] = None, parameters: Union[Mapping, NoneType] = None) -> Dict method of jikanpy.jikan.Jikan instance
    Gets user data

    Keyword Arguments:
    username -- MyAnimeList username
    request -- type of data to get (profile, history, friends, animelist, mangalist)
    argument -- data for history (anime, manga), page number for friends, type of list
    page -- page number for animelist and mangalist
    parameters -- dictionary containing key,value pairs for ?key=value in url query
```

As it says, for friends, you use `argument`, so:

`x = j.user(username='username', request='friends')`
`x = j.user(username='username', request='friends', argument=2)`
`x = j.user(username='username', request='friends', argument=3)`

This makes sense if you compare it to the urls generated by the user endpoint for animelist/mangalist:

`https://api.jikan.moe/v3/user/username/animelist/all/2`

vs for friends:

`https://api.jikan.moe/v3/user/username/friends/2`

So the argument (which is `all`/`completed`/`watching`) for the animelist endpoint is just a number for friends, so it just uses a number.

**Comment by sam5558** [comment]
Thank you,
I was using page instead of argument... Thank you @seanbreckenridge

**Comment by abhinavk99** [comment]
Closing since it seems you've got it figured out now
