### ISSUE TITLE
api error 403

### ISSUE THREAD

**Issue by Codeddeath03** [AWConant/jikanpy#66]
idk why but im getting ""An error occurred: Command raised an exception: APIException: 403 403 on https://myanimelist.net/anime.php?q=dragon+ball&type=1&score=0&status=0&p=0&r=0&sd=0&sm=0&sy=0&ed=0&em=0&ey=0&gx=0&c[]=a&c[]=b&c[]=c&c[]=f&c[]=d&c[]=e&c[]=g: error for search type=anime, query=dragon ball""
.

**Comment by irfan-dahir** [comment]
Was an API related issue - which should be fixed now.

Is this still occurring for you?

**Comment by Codeddeath03** [comment]
Nope, its working now, thx!

**Comment by gersongams** [comment]
It's happening again 😢

**Comment by irfan-dahir** [comment]
Issue with MAL.
https://github.com/jikan-me/jikan/issues/283
