### ISSUE TITLE
is there a way to select the first anime listed when searching for a title?

### ISSUE THREAD

**Issue by pleaselovemeuwu** [AWConant/jikanpy#67]
hi, ive been trying

from jikanpy import Jikan
jikan = Jikan()
result = jikan.search("anime", "Steins Gate")
print(result)

the result i get is

{'request_hash': 'request:search:4eedd7acd468d3a389d6f1ea076ee81cd7315f50', 'request_cached': True, 'request_cache_expiry': 432000, 'results': [{'mal_id': 9253, 'url': 'https://myanimelist.net/anime/9253/Steins_Gate', 'image_url': 'https://cdn.myanimelist.net/images/anime/5/73199.jpg?s=97b97d568f25a02cf5a22dda13b5371f', 'title': 'Steins;Gate', 'airing': False, 'synopsis': 'The self-proclaimed mad scientist Rintarou Okabe rents out a room in a rickety old building in Akihabara, where he indulges himself in his hobby of inventing prospective "future gadgets" with fellow l...', 'type': 'TV', 'episodes': 24, 'score': 9.13, 'start_date': '2011-04-06T00:00:00+00:00', 'end_date': '2011-09-14T00:00:00+00:00', 'members': 1425593, 'rated': 'PG-13'}, {'mal_id': 30484, 'url': 'https://myanimelist.net/anime/30484/Steins_Gate_0', 'image_url': 'https://cdn.myanimelist.net/images/anime/1375/93521.jpg?s=d4b7e6cbc3f675048b0f1e33adefe445', 'title': 'Steins;Gate 0', 'airing': False, 'synopsis': 'The eccentric, self-proclaimed mad scientist Rintarou Okabe has become a shell of his former self. Depressed and traumatized after failing to rescue his friend Makise Kurisu, he has decided to forsake...', 'type': 'TV', 'episodes': 23, 'score': 8.53, 'start_date': '2018-04-12T00:00:00+00:00', 'end_date': '2018-09-27T00:00:00+00:00', 'members': 459124, 'rated': 'PG-13'}...

so it returns a list of all listings that match what i searched for. but i cant figure out how to select, lets say the first result, so i can get the show id. it looks like it should be result.results[0].mal_id but i cant do that, and out of the sake of just trying stuff out i tried doing it without the [0]. this may be very obvious, but i cannot figure it out

**Comment by seanbreckenridge** [comment]
```
>>> import jikanpy
>>> jikan = jikanpy.Jikan()
>>> result = jikan.search("anime", "Steins Gate")
>>> result
{'request_hash': 'request:search:4eedd7acd468d3a389d6f1ea076ee81cd7315f50', 'request_cached': True, 'request_cache_expiry': 432000, 'results': [{'mal_id': 9253, 'url': 'https://myanimelist.net/anime/9253/Steins_Gate', 'image_url': 'https://cdn.myanimelist.net/images/anime/5/73199.jpg?s=97b97d568f25a02cf5a22dda13b5371f', 'title': 'Steins;Gate', 'airing': False, 'synopsis': 'The self-proclaimed mad scientist Rintarou Okabe rents out a room in a rickety old building in Akihabara, where he indulges himself in his hobby of inventing prospective "future gadgets" with fellow l...', 'type': 'TV', 'episodes': 24, 'score': 9.13, 'start_date': '2011-04-06T00:00:00+00:00', 'end_date': '2011-09-14T00:00:00+00:00', 'members': 1425593, 'rated': 'PG-13'}, {'mal_id': 30484, 'url': 'https://myanimelist.net/anime/30484/Steins_Gate_0....
>>> result.keys()
dict_keys(['request_hash', 'request_cached', 'request_cache_expiry', 'results', 'last_page', 'jikan_url', 'headers'])
>>> result["results"][0]
{'mal_id': 9253, 'url': 'https://myanimelist.net/anime/9253/Steins_Gate', 'image_url': 'https://cdn.myanimelist.net/images/anime/5/73199.jpg?s=97b97d568f25a02cf5a22dda13b5371f', 'title': 'Steins;Gate', 'airing': False, 'synopsis': 'The self-proclaimed mad scientist Rintarou Okabe rents out a room in a rickety old building in Akihabara, where he indulges himself in his hobby of inventing prospective "future gadgets" with fellow l...', 'type': 'TV', 'episodes': 24, 'score': 9.13, 'start_date': '2011-04-06T00:00:00+00:00', 'end_date': '2011-09-14T00:00:00+00:00', 'members': 1425593, 'rated': 'PG-13'}
>>> result["results"][0]['mal_id']
9253
>>> result["results"][0]['title']
'Steins;Gate'
```

**Comment by pleaselovemeuwu** [comment]
my hero, thank you
