### ISSUE TITLE
egg_info Error

### ISSUE THREAD

**Issue by LordDamionDevil** [AWConant/jikanpy#7]
Everytime i try installing this over pip it ends up giving an egg_info error:
`Collecting git+git://github.com/AWConant/jikanpy.git (from -r requirements_no_audio.txt (line 7))
  Cloning git://github.com/AWConant/jikanpy.git to c:\users\user\appdata\local\temp\pip-req-build-xmd4dbdu
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-req-build-xmd4dbdu\\setup.py'
Command "python setup.py egg_info" failed with error code 1 in C:\Users\User\AppData\Local\Temp\pip-req-build-xmd4dbdu\`

OS: Windows 10

**Comment by abhinavk99** [comment]
Did you fix it? I was just wondering since you closed the issue.

**Comment by abhinavk99** [comment]
I forgot to include a setup.py file. Installation should work now that I added it.
